/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilitaRouteImport } from './routes/utilita'
import { Route as TerminiRouteImport } from './routes/termini'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ScorteRouteImport } from './routes/scorte'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DesignRouteImport } from './routes/design'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as QualeConvieneRouteRouteImport } from './routes/quale-conviene/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QualeConvieneIndexRouteImport } from './routes/quale-conviene/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as QualeConvieneConfrontaRouteImport } from './routes/quale-conviene/confronta'
import { Route as QualeConvieneCategoryRouteImport } from './routes/quale-conviene/$category'

const UtilitaRoute = UtilitaRouteImport.update({
  id: '/utilita',
  path: '/utilita',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorteRoute = ScorteRouteImport.update({
  id: '/scorte',
  path: '/scorte',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const QualeConvieneRouteRoute = QualeConvieneRouteRouteImport.update({
  id: '/quale-conviene',
  path: '/quale-conviene',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QualeConvieneIndexRoute = QualeConvieneIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QualeConvieneRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const QualeConvieneConfrontaRoute = QualeConvieneConfrontaRouteImport.update({
  id: '/confronta',
  path: '/confronta',
  getParentRoute: () => QualeConvieneRouteRoute,
} as any)
const QualeConvieneCategoryRoute = QualeConvieneCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => QualeConvieneRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/quale-conviene': typeof QualeConvieneRouteRouteWithChildren
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/design': typeof DesignRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scorte': typeof ScorteRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termini': typeof TerminiRoute
  '/utilita': typeof UtilitaRoute
  '/quale-conviene/$category': typeof QualeConvieneCategoryRoute
  '/quale-conviene/confronta': typeof QualeConvieneConfrontaRoute
  '/app/': typeof AppIndexRoute
  '/quale-conviene/': typeof QualeConvieneIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/design': typeof DesignRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scorte': typeof ScorteRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termini': typeof TerminiRoute
  '/utilita': typeof UtilitaRoute
  '/quale-conviene/$category': typeof QualeConvieneCategoryRoute
  '/quale-conviene/confronta': typeof QualeConvieneConfrontaRoute
  '/app': typeof AppIndexRoute
  '/quale-conviene': typeof QualeConvieneIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/quale-conviene': typeof QualeConvieneRouteRouteWithChildren
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/design': typeof DesignRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scorte': typeof ScorteRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termini': typeof TerminiRoute
  '/utilita': typeof UtilitaRoute
  '/quale-conviene/$category': typeof QualeConvieneCategoryRoute
  '/quale-conviene/confronta': typeof QualeConvieneConfrontaRoute
  '/app/': typeof AppIndexRoute
  '/quale-conviene/': typeof QualeConvieneIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/quale-conviene'
    | '/contatti'
    | '/cookie'
    | '/design'
    | '/privacy'
    | '/robots.txt'
    | '/scorte'
    | '/sign-in'
    | '/sitemap.xml'
    | '/termini'
    | '/utilita'
    | '/quale-conviene/$category'
    | '/quale-conviene/confronta'
    | '/app/'
    | '/quale-conviene/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contatti'
    | '/cookie'
    | '/design'
    | '/privacy'
    | '/robots.txt'
    | '/scorte'
    | '/sign-in'
    | '/sitemap.xml'
    | '/termini'
    | '/utilita'
    | '/quale-conviene/$category'
    | '/quale-conviene/confronta'
    | '/app'
    | '/quale-conviene'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/quale-conviene'
    | '/contatti'
    | '/cookie'
    | '/design'
    | '/privacy'
    | '/robots.txt'
    | '/scorte'
    | '/sign-in'
    | '/sitemap.xml'
    | '/termini'
    | '/utilita'
    | '/quale-conviene/$category'
    | '/quale-conviene/confronta'
    | '/app/'
    | '/quale-conviene/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  QualeConvieneRouteRoute: typeof QualeConvieneRouteRouteWithChildren
  ContattiRoute: typeof ContattiRoute
  CookieRoute: typeof CookieRoute
  DesignRoute: typeof DesignRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ScorteRoute: typeof ScorteRoute
  SignInRoute: typeof SignInRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminiRoute: typeof TerminiRoute
  UtilitaRoute: typeof UtilitaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilita': {
      id: '/utilita'
      path: '/utilita'
      fullPath: '/utilita'
      preLoaderRoute: typeof UtilitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorte': {
      id: '/scorte'
      path: '/scorte'
      fullPath: '/scorte'
      preLoaderRoute: typeof ScorteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quale-conviene': {
      id: '/quale-conviene'
      path: '/quale-conviene'
      fullPath: '/quale-conviene'
      preLoaderRoute: typeof QualeConvieneRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quale-conviene/': {
      id: '/quale-conviene/'
      path: '/'
      fullPath: '/quale-conviene/'
      preLoaderRoute: typeof QualeConvieneIndexRouteImport
      parentRoute: typeof QualeConvieneRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/quale-conviene/confronta': {
      id: '/quale-conviene/confronta'
      path: '/confronta'
      fullPath: '/quale-conviene/confronta'
      preLoaderRoute: typeof QualeConvieneConfrontaRouteImport
      parentRoute: typeof QualeConvieneRouteRoute
    }
    '/quale-conviene/$category': {
      id: '/quale-conviene/$category'
      path: '/$category'
      fullPath: '/quale-conviene/$category'
      preLoaderRoute: typeof QualeConvieneCategoryRouteImport
      parentRoute: typeof QualeConvieneRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface QualeConvieneRouteRouteChildren {
  QualeConvieneCategoryRoute: typeof QualeConvieneCategoryRoute
  QualeConvieneConfrontaRoute: typeof QualeConvieneConfrontaRoute
  QualeConvieneIndexRoute: typeof QualeConvieneIndexRoute
}

const QualeConvieneRouteRouteChildren: QualeConvieneRouteRouteChildren = {
  QualeConvieneCategoryRoute: QualeConvieneCategoryRoute,
  QualeConvieneConfrontaRoute: QualeConvieneConfrontaRoute,
  QualeConvieneIndexRoute: QualeConvieneIndexRoute,
}

const QualeConvieneRouteRouteWithChildren =
  QualeConvieneRouteRoute._addFileChildren(QualeConvieneRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  QualeConvieneRouteRoute: QualeConvieneRouteRouteWithChildren,
  ContattiRoute: ContattiRoute,
  CookieRoute: CookieRoute,
  DesignRoute: DesignRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ScorteRoute: ScorteRoute,
  SignInRoute: SignInRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminiRoute: TerminiRoute,
  UtilitaRoute: UtilitaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
