/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UtilitaRouteImport } from './routes/utilita'
import { Route as TerminiRouteImport } from './routes/termini'
import { Route as ScorteRouteImport } from './routes/scorte'
import { Route as QualeConvieneRouteImport } from './routes/quale-conviene'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DesignRouteImport } from './routes/design'
import { Route as CookieRouteImport } from './routes/cookie'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'

const UtilitaRoute = UtilitaRouteImport.update({
  id: '/utilita',
  path: '/utilita',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const ScorteRoute = ScorteRouteImport.update({
  id: '/scorte',
  path: '/scorte',
  getParentRoute: () => rootRouteImport,
} as any)
const QualeConvieneRoute = QualeConvieneRouteImport.update({
  id: '/quale-conviene',
  path: '/quale-conviene',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieRoute = CookieRouteImport.update({
  id: '/cookie',
  path: '/cookie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/design': typeof DesignRoute
  '/privacy': typeof PrivacyRoute
  '/quale-conviene': typeof QualeConvieneRoute
  '/scorte': typeof ScorteRoute
  '/termini': typeof TerminiRoute
  '/utilita': typeof UtilitaRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/design': typeof DesignRoute
  '/privacy': typeof PrivacyRoute
  '/quale-conviene': typeof QualeConvieneRoute
  '/scorte': typeof ScorteRoute
  '/termini': typeof TerminiRoute
  '/utilita': typeof UtilitaRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/contatti': typeof ContattiRoute
  '/cookie': typeof CookieRoute
  '/design': typeof DesignRoute
  '/privacy': typeof PrivacyRoute
  '/quale-conviene': typeof QualeConvieneRoute
  '/scorte': typeof ScorteRoute
  '/termini': typeof TerminiRoute
  '/utilita': typeof UtilitaRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/contatti'
    | '/cookie'
    | '/design'
    | '/privacy'
    | '/quale-conviene'
    | '/scorte'
    | '/termini'
    | '/utilita'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contatti'
    | '/cookie'
    | '/design'
    | '/privacy'
    | '/quale-conviene'
    | '/scorte'
    | '/termini'
    | '/utilita'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/contatti'
    | '/cookie'
    | '/design'
    | '/privacy'
    | '/quale-conviene'
    | '/scorte'
    | '/termini'
    | '/utilita'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ContattiRoute: typeof ContattiRoute
  CookieRoute: typeof CookieRoute
  DesignRoute: typeof DesignRoute
  PrivacyRoute: typeof PrivacyRoute
  QualeConvieneRoute: typeof QualeConvieneRoute
  ScorteRoute: typeof ScorteRoute
  TerminiRoute: typeof TerminiRoute
  UtilitaRoute: typeof UtilitaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/utilita': {
      id: '/utilita'
      path: '/utilita'
      fullPath: '/utilita'
      preLoaderRoute: typeof UtilitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scorte': {
      id: '/scorte'
      path: '/scorte'
      fullPath: '/scorte'
      preLoaderRoute: typeof ScorteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quale-conviene': {
      id: '/quale-conviene'
      path: '/quale-conviene'
      fullPath: '/quale-conviene'
      preLoaderRoute: typeof QualeConvieneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie': {
      id: '/cookie'
      path: '/cookie'
      fullPath: '/cookie'
      preLoaderRoute: typeof CookieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ContattiRoute: ContattiRoute,
  CookieRoute: CookieRoute,
  DesignRoute: DesignRoute,
  PrivacyRoute: PrivacyRoute,
  QualeConvieneRoute: QualeConvieneRoute,
  ScorteRoute: ScorteRoute,
  TerminiRoute: TerminiRoute,
  UtilitaRoute: UtilitaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
